---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-app-service
                port:
                  number: {{ .Values.service.port }}
