apiVersion: v1
kind: Service
metadata:
  name: dummy-app-service
  labels:
    app: dummy-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dummy-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      
