name: dummy-pdf-or-png
on:
  pull_request:
    paths:
      - "dummy-pdf-or-png/**"
      - ".github/workflows/go.yaml"
  push:
    branches:
      - main
    paths:
      - "dummy-pdf-or-png/**"
      - ".github/workflows/go.yaml"
  workflow_dispatch:

jobs:  
  build-and-test-go:
    name: "Build & Test Go"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail ./dummy-pdf-or-png'

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./dummy-pdf-or-png
          push: false
          tags: dummy-pdf-or-png:latest