name: Push to GCR GitHub Action
on:
  workflow_dispatch:
  push:
    paths:
      - "dummy-pdf-or-png/**"
    branches:
      - main
  pull_request:
    paths:
      - "dummy-pdf-or-png/**"
    branches:
      - master

# env:
#   ENV: dev
#   GPC_ARTIFACT_REGISTRY_HOST: europe-west3-docker.pkg.dev
#   GPC_ARTIFACT_REGISTRY_REPO: "dummy-pdf-or-png"

jobs:
  checkout-and-auth:
    uses: ./.github/workflows/auth.yml
  build-and-push-to-gcr:
    name: "Golang"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA }}

      - name: Build and push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: dummy-pdf-or-png/demo
          image_tag: latest,v1
          context: ./dummy-pdf-or-png