name: Build and Push Go
on:
  push:
    paths:
      - "dummy-pdf-or-png/**"
      - ".github/workflows/go.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "dummy-pdf-or-png/**"
      - ".github/workflows/go.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:  
  build-and-push-to-gcr:
    name: "Golang"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA }}

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail ./dummy-pdf-or-png'

      - name: Build
        uses: docker/build-push-action@v4
        if: github.event.pull_request.base.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        with:
          context: ./dummy-pdf-or-png
          push: false
          tags: europe-west3-docker.pkg.dev/${{ env.GCP_PROJECT }}/dummy-pdf-or-png/demo:latest

      - name: Build & Push
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: dummy-pdf-or-png/demo
          image_tag: latest,v1
          context: ./dummy-pdf-or-png
          #push_only: true # does not work if tag does not exist
