name: Push to GCR GitHub Action
on:
  push:
    paths:
      - "dummy-pdf-or-png/**"
    branches:
      - main
  pull_request:
    paths:
      - "dummy-pdf-or-png/**"

env:
  ENV: dev
  GCP_PROJECT: "dev-demo-codrin-h"
  GPC_ARTIFACT_REGISTRY_HOST: europe-west3-docker.pkg.dev
  GPC_ARTIFACT_REGISTRY_REPO: "dummy-pdf-or-png"

jobs:
  build-and-push-to-gcr:
    name: "Golang"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/615713427419/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "dev-github-runner-sa@dev-demo-codrin-h.iam.gserviceaccount.com"

      # # This example uses the docker login action
      # - uses: "docker/login-action@v1"
      #   with:
      #     registry: $GPC_ARTIFACT_REGISTRY_HOST
      #     username: "oauth2accesstoken"
      #     password: "${{ steps.auth.outputs.access_token }}"

      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: dev-demo-codrin-h
          image_name: dummy-pdf-or-png
          image_tag: latest,v1
          dockerfile: ./dummy-pdf-or-png/Dockerfile
          context: .