name: Push to GCR GitHub Action
on:
  push:
    paths:
      - "dummy-pdf-or-png/**"
    branches:
      - main
  pull_request:
    paths:
      - "dummy-pdf-or-png/**"

env:
  ENV: dev
  GPC_ARTIFACT_REGISTRY_HOST: europe-west3-docker.pkg.dev
  GPC_ARTIFACT_REGISTRY_REPO: "dummy-pdf-or-png"

jobs:
  build-and-push-to-gcr:
    name: "Golang"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.GCP_SA }}

      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: dummy-pdf-or-png/demo
          image_tag: latest,v1
          context: ./dummy-pdf-or-png