name: Terraform CI
on:
  push:
    paths:
      - 'iac/**'
      - ".github/workflows/iac.yaml"
    branches:
      - main
  pull_request:
    paths:
      - 'iac/**'
      - ".github/workflows/iac.yaml"
    branches:
      - master
env:
  ENV: dev
  PROJECT_ID: dev-demo-codrin-h
  GAR_LOCATION: europe-west3-c
  GKE_CLUSTER: primary
  GKE_ZONE: europe-west3-c

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/615713427419/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "dev-github-runner-sa@dev-demo-codrin-h.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./iac/terraform
        run: terraform init -backend-config=environments/$ENV/config.gcs.tfbackend

      - name: Terraform Format
        working-directory: ./iac/terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./iac/terraform
        run: terraform plan --var-file environments/$ENV/$ENV.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./iac/terraform
        run: terraform apply -auto-approve --var-file environments/$ENV/$ENV.tfvars
