name: dummy-app
on:
  pull_request:
    paths:
      - "dummy-app/**"
      - ".github/workflows/java.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test-java:
    name: "Build & Test"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./dummy-app
          push: false
          tags: europe-west3-docker.pkg.dev/${{ env.GCP_PROJECT }}/dummy-app/dummy-app:latest
          build-args: BUILD_TAG=latest
