name: dummy-app
on:
  pull_request:
    paths:
      - "dummy-app/**"
      - ".github/workflows/java.yaml"
  push:
    branches:
      - main
    paths:
      - "dummy-app/**"
      - ".github/workflows/java.yaml"
  workflow_dispatch:

jobs:
  build-and-test-java:
    name: "Build & Test"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./dummy-app
          push: false
          tags: dummy-app:latest
          build-args: BUILD_TAG=latest
