name: Build and Push Java
on:
  push:
    paths:
      - "dummy-app/**"
    branches:
      - main
  pull_request:
    paths:
      - "dummy-app/**"
    branches:
      - master

# env:
#   ENV: dev
#   GPC_ARTIFACT_REGISTRY_HOST: europe-west3-docker.pkg.dev
#   GPC_ARTIFACT_REGISTRY_REPO: "dummy-app"

jobs:
  build-and-push-to-gcr:
    name: "Java"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: europe-west3-docker.pkg.dev/${{ env.GCP_PROJECT }}/dummy-app/demo:latest

      - name: Push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: dummy-app/demo
          image_tag: latest,v1
          context: ./dummy-app
          push_only: true