name: release
on:
  push:
    tags:        
      - '*'

jobs:  
  build-and-push-to-gcr:
    name: "Relase"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA }}

      - name: Build & Push
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: dummy-pdf-or-png/dummy-pdf-or-png
          image_tag: latest,${{ github.ref }}
          context: ./dummy-pdf-or-png

      - name: Build & Push
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: dummy-app/dummy-app
          image_tag: latest${{ github.ref }}
          context: ./dummy-app
          build_args: BUILD_TAG=${{ github.ref }}

      - uses: azure/setup-helm@v3
      
      - id: helm-build-push-install
        working-directory: ./charts
        run: |
          helm package ./dummy-app/ --version ${{ github.ref }} --app-version ${{ github.ref }}
          helm package ./dummy-pdf-or-png/ --version ${{ github.ref }} --app-version ${{ github.ref }}
          helm push dummy-app-${{ github.ref }}.tgz oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-app
          helm push dummy-pdf-or-png-${{ github.ref }}.tgz oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-app
          helm upgrade -i dummy-app oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-app/dummy-app --version ${{ github.ref }}
          helm upgrade -i dummy-app oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-app/dummy-app --version ${{ github.ref }}
