name: release
on:
  push:
    tags:        
      - '*'

jobs:  
  build-and-push-to-gcr:
    name: "Relase"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA }}

      - name: Authenticate to GKE
        id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'primary'
          location: 'europe-west3-a'

      - name: Configure docker
        run: |-
          gcloud --quiet auth configure-docker europe-west3-docker.pkg.dev

      - name: Build & Push - dummy-pdf-or-png
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: docker-dummy-pdf-or-png/dummy-pdf-or-png
          image_tag: latest,${{ github.ref_name }}
          context: ./dummy-pdf-or-png

      - name: Build & Push - dummy-app
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: ${{ env.GCP_PROJECT }}
          image_name: docker-dummy-app/dummy-app
          image_tag: latest,${{ github.ref_name }}
          context: ./dummy-app
          build_args: BUILD_TAG=${{ github.ref_name }}

      - name: Helm install
        uses: azure/setup-helm@v3
      
      - name: Helm package, push & install
        id: helm-package-push-install
        working-directory: ./charts
        run: |
          helm package ./dummy-app/ --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
          helm package ./dummy-pdf-or-png/ --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
          helm push dummy-app-${{ github.ref_name }}.tgz oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-app
          helm push dummy-pdf-or-png-${{ github.ref_name }}.tgz oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-pdf-or-png
          helm upgrade -i dummy-app oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-app --version ${{ github.ref_name }}
          helm upgrade -i dummy-pdf-or-png oci://europe-west3-docker.pkg.dev/dev-demo-codrin-h/helm-dummy-pdf-or-png  --version ${{ github.ref_name }}
